"""
URL configuration for the API app.

This file defines the URL patterns for our Task API endpoints.
It connects URLs to views (ViewSets) using Django REST Framework's router.

Why use a router?
- Automatically generates URL patterns for ViewSet actions
- Provides a consistent URL structure
- Less code compared to manually defining each URL pattern
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet

# Create a router instance
# DefaultRouter automatically creates URL patterns for ViewSet actions
router = DefaultRouter()

# Register the TaskViewSet with the router
# This automatically creates the following URLs:
# - GET, POST /api/tasks/ (list all tasks, create new task)
# - GET, PUT, PATCH, DELETE /api/tasks/{id}/ (get, update, delete specific task)
# The 'tasks' part is the URL prefix (you can change it to whatever you want)
router.register(r'tasks', TaskViewSet, basename='task')

# Define the URL patterns for this app
urlpatterns = [
    # Include all URLs generated by the router
    # This means all the CRUD endpoints will be available
    path('', include(router.urls)),
]


